# MySQL Setup
SET default_storage_engine=InnoDB;
USE task_organizer;

DROP TABLE IF EXISTS user_task_mapping;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS task;

CREATE TABLE user (
`userid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`username` VARCHAR(25) NOT NULL UNIQUE,
`password` VARCHAR(50) NOT NULL,
`role` VARCHAR(50) DEFAULT 'user'
)ENGINE=InnoDB;

CREATE TABLE task (
`taskid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`taskname` VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE user_task_mapping (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, userid INT, taskid INT, completed BOOLEAN,
   FOREIGN KEY (userid) REFERENCES user(userid)
   ON DELETE CASCADE,
   FOREIGN KEY (taskid) REFERENCES task(taskid)
   ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE dummy (
`dummyid` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`dummyname` VARCHAR(50) NOT NULL UNIQUE
)ENGINE=InnoDB;